#!/usr/bin/env bash
# scripts/gen-swap-config.sh — emit llama-swap.yaml from config.sh.
# Usage: gen-swap-config.sh [output-file]
#   output-file defaults to <repo-root>/llama-swap.yaml
# Accepts CONFIG_FILE env var to override the config path (used in tests).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${CONFIG_FILE:-$REPO/config.sh}"
OUTPUT="${1:-$REPO/llama-swap.yaml}"

# Source config — gives us MODELS, CONTEXT, N_PARALLEL, EXTRA_FLAGS, MODEL_CONTEXT, TOOLBOX.
# shellcheck source=../config.sh
source "$CONFIG_FILE"

# Guard: MODELS must be non-empty or the generated YAML would have no models.
if [[ ${#MODELS[@]} -eq 0 ]]; then
  printf 'gen-swap-config: MODELS is empty in %s — nothing to generate\n' "$CONFIG_FILE" >&2
  exit 1
fi

# ---- helpers ----------------------------------------------------------------

# Escape dots in a path for use as a grep/pkill -f literal pattern.
escape_path() {
  printf '%s' "$1" | sed 's/\./\\./g'
}

# Build the cmdStop shell snippet for one model path.
# Pattern: toolbox run -c <toolbox> bash -c '...'
# The inner script does SIGTERM, waits up to 5 s, then SIGKILL.
make_cmd_stop() {
  local path="$1"
  local esc
  esc="$(escape_path "$path")"
  local pat='"-m '"$esc"'"'
  printf "toolbox run -c %s bash -c 'pkill -TERM -f -- %s; for i in 1 2 3 4 5; do pgrep -f -- %s >/dev/null || exit 0; sleep 1; done; pkill -KILL -f -- %s'" \
    "$TOOLBOX" "$pat" "$pat" "$pat"
}

# ---- build EXTRA_FLAGS string -----------------------------------------------
FLAGS_STR="${EXTRA_FLAGS[*]}"

# ---- emit YAML --------------------------------------------------------------
{
  printf '# GENERATED from config.sh — edit config.sh and run scripts/gen-swap-config.sh\n'
  printf '# Do not edit this file directly.\n'
  printf '\n'
  printf 'healthCheckTimeout: 900\n'
  printf 'logLevel: info\n'
  printf '\n'
  printf 'macros:\n'
  printf '  llama: >\n'
  printf '    toolbox run -c %s llama-server\n' "$TOOLBOX"
  printf '    --host 127.0.0.1 --port ${PORT}\n'
  printf '    -c %s -np %s\n' "$CONTEXT" "$N_PARALLEL"
  printf '    %s\n' "$FLAGS_STR"
  printf '\n'
  printf 'models:\n'

  for entry in "${MODELS[@]}"; do
    key="${entry%%|*}"
    path="${entry#*|}"

    # Per-model context override.
    ctx="$CONTEXT"
    if [[ -n "${MODEL_CONTEXT[$key]:-}" ]]; then
      ctx="${MODEL_CONTEXT[$key]}"
    fi

    cmd_stop="$(make_cmd_stop "$path")"

    printf '  %s:\n' "$key"
    if [[ "$ctx" != "$CONTEXT" ]]; then
      # Per-model context override: append -c after the macro — llama-server
      # takes the last occurrence of a repeated flag, so this wins.
      printf '    # context override: %s tokens\n' "$ctx"
      printf '    cmd: ${llama} -m %s -c %s\n' "$path" "$ctx"
    else
      printf '    cmd: ${llama} -m %s\n' "$path"
    fi
    printf '    cmdStop: %s\n' "$cmd_stop"
    printf '\n'
  done
} > "$OUTPUT"

echo "Written: $OUTPUT"
